Set NODE_ENV to production, use node user
api3dao/airseeker pull request #203
Opened 2024-03-11 19:24 UTC by Siegrift

Closes https://github.com/api3dao/airseeker-v2/issues/199

2024-03-12 08:57 UTC, bdrhn9 requested changes

2024-03-12 08:57 UTC, bdrhn9 commented on docker/Dockerfile
>  RUN pnpm fetch
When I try to build the image I got the following error at `RUN pnpm fetch` step:

```
 => [3/8] RUN npm install -g pnpm                                                                                                         1.7s
 => [4/8] COPY --chown=node:node pnpm-lock.yaml /app                                                                                      0.0s
 => ERROR [5/8] RUN pnpm fetch                                                                                                            0.9s
------                                                                                                                                         
 > [5/8] RUN pnpm fetch:
0.898  EACCES  EACCES: permission denied, open '/app/_tmp_1_5a8578c4de70d1f92035f168d4c8f1cf'
0.898 
0.898 
0.898 
------
Dockerfile:16
--------------------
  14 |     # lockfile has changed (otherwise uses the cached value).
  15 |     COPY --chown=node:node pnpm-lock.yaml /app
  16 | >>> RUN pnpm fetch
  17 |     # Copies all of the contents (without files listed in .dockerignore) of the monorepo into the image.
  18 |     COPY --chown=node:node . /app
--------------------
ERROR: failed to solve: process "/bin/sh -c pnpm fetch" did not complete successfully: exit code: 1
```

Solution would be installing all required packages as a root in the Dockerfile, and at the end of the file switching to image user to `node` by just adding `USER node` like following:
```dockerfile
FROM node:18-alpine
ENV name="airseeker"
LABEL application="airseeker" description="Airseeker container"
WORKDIR /app

# Install pnpm globally (needs root privileges).
RUN npm install -g pnpm

# Copy just the "pnpm-lock.yaml" file and use "pnpm fetch" to download all dependencies just from the lockfile. This
# command is specifically designed to improve building a docker image because it only installs the dependencies if the
# lockfile has changed (otherwise uses the cached value).
COPY pnpm-lock.yaml /app
RUN pnpm fetch
# Copies all of the contents (without files listed in .dockerignore) of the monorepo into the image.
COPY . /app
# Ideally, we would use "--offline" option, but it seems pnpm has a bug. Fortunately, the instalation times are similar.
# See: https://github.com/pnpm/pnpm/issues/6058 for details.
RUN pnpm install --prefer-offline
RUN pnpm run build

# "node" Docker images come with a built-in, least-privileged user called "node"
USER node

# Start the Airseeker.
ENV NODE_ENV=production
ENTRYPOINT ["node", "dist/index.js"]
```

That would work (even though `node` user isn't owner of the `/app` directory, `others` have right to read files under `/app`) if we don't utilize some trick to not read config file from S3 on Cloudformation like this:
```
mkdir -p /app/config && echo -e $AIRSEEKER_JSON > /app/config/airseeker.json && IFS= && echo -e $SECRETS_ENV > /app/config/secrets.env && node /app/dist/index.js
```

My solution would be adding this line before setting user `RUN chown -R node:node /app/config`. We can also choose `RUN chown -R node:node /app`. If we choose first, we can guarantee that we sealed all packages except config folder which is one we can expect to be changed dynamically. So:

```dockerfile
FROM node:18-alpine
ENV name="airseeker"
LABEL application="airseeker" description="Airseeker container"
WORKDIR /app

# Install pnpm globally (needs root privileges).
RUN npm install -g pnpm

# Copy just the "pnpm-lock.yaml" file and use "pnpm fetch" to download all dependencies just from the lockfile. This
# command is specifically designed to improve building a docker image because it only installs the dependencies if the
# lockfile has changed (otherwise uses the cached value).
COPY pnpm-lock.yaml /app
RUN pnpm fetch
# Copies all of the contents (without files listed in .dockerignore) of the monorepo into the image.
COPY . /app
# Ideally, we would use "--offline" option, but it seems pnpm has a bug. Fortunately, the instalation times are similar.
# See: https://github.com/pnpm/pnpm/issues/6058 for details.
RUN pnpm install --prefer-offline
RUN pnpm run build

RUN chown -R node:node /app/config

# "node" Docker images come with a built-in, least-privileged user called "node"
USER node

# Start the Airseeker.
ENV NODE_ENV=production
ENTRYPOINT ["node", "dist/index.js"]
```

2024-03-12 09:00 UTC, Siegrift commented on docker/Dockerfile
>  RUN pnpm fetch
Thanks. I actually haven't built it myself, because I thought it's going to be check by CI, but we only have that in Signed API repo 🤦 .

2024-03-12 09:25 UTC, bdrhn9 approved these changes

2024-03-14 07:30 UTC, Siegrift commented on docker/Dockerfile
>  RUN pnpm fetch
I've made a slight change to chown over the whole `/app` folder as it was done by this image previosuly (`chown -R airseeker /app`). This is the same way how it's done in Signed API.

2024-03-14 07:31 UTC, merged